<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE keyboardShortcutContainer [

<!ELEMENT keyboardShortcutContainer     (windowName, keyboardShortcut+) >
<!ELEMENT windowName                    (#PCDATA) >
<!ELEMENT keyboardShortcut              (action, key+) >
<!ELEMENT action                        (#PCDATA) >
<!ELEMENT key                           (#PCDATA) >

]>

<keyboardShortcutContainer>
    <windowName>hiMyNameIsWindow</windowName>
    <keyboardShortcut>
        <action>playAudio</action>
        <key>P</key>
    </keyboardShortcut>
    <keyboardShortcut>
        <action>pauseAudio</action>
        <key>Ctrl-P</key>
        <key>Space</key>
    </keyboardShortcut>
</keyboardShortcutContainer>
