<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE scheduler [

<!ELEMENT scheduler (user,
                     connectionManagerFactory,
                     authenticationClientFactory,
                     storageClientFactory,
                     scheduleFactory,
                     playLogFactory,
                     backupFactory,
                     audioPlayer,
                     xmlRpcDaemon) >

<!ELEMENT connectionManagerFactory  (simpleConnectionManager) >

<!ELEMENT simpleConnectionManager   EMPTY >
<!ATTLIST simpleConnectionManager   dsn         CDATA   #REQUIRED >
<!ATTLIST simpleConnectionManager   userName    CDATA   #REQUIRED >
<!ATTLIST simpleConnectionManager   password    CDATA   #REQUIRED >

<!ELEMENT authenticationClientFactory (testAuthentication|
                                       webAuthentication)>

<!ELEMENT testAuthentication (user) >

<!ELEMENT user EMPTY >
<!ATTLIST user login        CDATA       #REQUIRED >
<!ATTLIST user password     CDATA       #REQUIRED >

<!ELEMENT webAuthentication (location) >

<!ELEMENT location EMPTY >
<!ATTLIST location server   CDATA       #REQUIRED >
<!ATTLIST location port     NMTOKEN     #REQUIRED >
<!ATTLIST location path     CDATA       #REQUIRED >

<!ELEMENT storageClientFactory (testStorage|webStorage) >

<!ELEMENT testStorage (playlist*, audioClip*) >
<!ATTLIST testStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT webStorage (location) >
<!ATTLIST webStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement ((audioClip|playlist), fadeInfo?) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip title           CDATA       #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #REQUIRED >

<!ELEMENT fadeInfo EMPTY >
<!ATTLIST fadeInfo id              NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeIn          NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeOut         NMTOKEN     #REQUIRED >

<!ELEMENT scheduleFactory (postgresqlSchedule) >
<!ELEMENT postgresqlSchedule EMPTY >

<!ELEMENT playLogFactory (postgresqlPlayLog) >
<!ELEMENT postgresqlPlayLog EMPTY >

<!ELEMENT backupFactory (postgresqlBackup) >
<!ELEMENT postgresqlBackup EMPTY >

<!ELEMENT audioPlayer   (gstreamerPlayer) >

<!ELEMENT gstreamerPlayer   EMPTY >
<!ATTLIST gstreamerPlayer   audioDevice  CDATA   #IMPLIED  >

<!ELEMENT xmlRpcDaemon EMPTY >
<!ATTLIST xmlRpcDaemon xmlRpcHost   CDATA          #REQUIRED >
<!ATTLIST xmlRpcDaemon xmlRpcPort   NMTOKEN        #REQUIRED >
<!ATTLIST xmlRpcDaemon pidFileName  CDATA          #REQUIRED >
<!ATTLIST xmlRpcDaemon background   (true|false)   "true"    >

]>
<scheduler>
    <user login="root" password="q" />

    <connectionManagerFactory>
        <simpleConnectionManager    dsn      = "Campcaster-test"
                                    userName = "test"
                                    password = "test"
        />
    </connectionManagerFactory>

    <authenticationClientFactory>
        <webAuthentication>
            <location server="localhost" port="80"
                      path="/campcasterStorageServer/xmlrpc/xrLocStor.php" />
        </webAuthentication>
    </authenticationClientFactory>

    <storageClientFactory>
        <webStorage tempFiles="file:///tmp/campcasterSchedulerStorageClient" >
            <location server="localhost" port="80" 
                      path="/campcasterStorageServer/xmlrpc/xrLocStor.php" />
        </webStorage>
    </storageClientFactory>

    <scheduleFactory>
        <postgresqlSchedule/>
    </scheduleFactory>

    <playLogFactory>
        <postgresqlPlayLog/>
    </playLogFactory>

    <backupFactory>
        <postgresqlBackup/>
    </backupFactory>

    <audioPlayer>
        <gstreamerPlayer audioDevice = "default" />
    </audioPlayer>

    <xmlRpcDaemon xmlRpcHost  = "localhost"
                  xmlRpcPort  = "3344"
                  pidFileName = "tmp/scheduler.pid"
    />
</scheduler>

