<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE metadataTypeContainer [

<!ELEMENT metadataTypeContainer           (metadataType+)       >

<!ELEMENT metadataType                    (constraint?)         >
<!ATTLIST metadataType  dcName            NMTOKEN     #REQUIRED >
<!ATTLIST metadataType  id3Tag            CDATA       #IMPLIED  >
<!ATTLIST metadataType  localizationKey   CDATA       #REQUIRED >
<!ATTLIST metadataType  tab               NMTOKEN     #IMPLIED  >

<!ELEMENT constraint                      (value*)              >
<!ATTLIST constraint    type              NMTOKEN     #REQUIRED >

<!ELEMENT value                           (#PCDATA)             >

]>

<metadataTypeContainer>
    <metadataType   dcName          = "dc:title"
                    id3Tag          = "TIT2"
                    localizationKey = "title"
                    tab             = "main"
    />
    <metadataType   dcName          = "dc:creator"
                    id3Tag          = "TPE1"
                    localizationKey = "creator"
                    tab             = "main"
    />
    <metadataType   dcName          = "dc:source"
                    id3Tag          = "TALB"
                    localizationKey = "album"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:year"
                    id3Tag          = "TYER"
                    localizationKey = "year"
                    tab             = "music" >
        <constraint type            = "numericRange" >
            <value>0</value>
            <value>3000</value>
        </constraint>
    </metadataType>
    <metadataType   dcName          = "dc:type"
                    id3Tag          = "TCON"
                    localizationKey = "genre"
                    tab             = "main"
    />
    <metadataType   dcName          = "dc:description"
                    id3Tag          = "COMM"
                    localizationKey = "description"
                    tab             = "main"
    />
    <metadataType   dcName          = "dc:format"
                    localizationKey = "format" >
        <constraint type            = "enumeration" >
            <value>mp3</value>
            <value>mpeg</value>
            <value>ogg</value>
        </constraint>
    </metadataType>
    <metadataType   dcName          = "ls:bpm"
                    id3Tag          = "TBPM"
                    localizationKey = "bpm"
                    tab             = "music" >
        <constraint type            = "numeric" />
    </metadataType>
    <metadataType   dcName          = "ls:rating"
                    id3Tag          = "POPM"
                    localizationKey = "rating"
                    tab             = "music"
    />
    <metadataType   dcName          = "dcterms:extent"
                    localizationKey = "length"
    />
    <metadataType   dcName          = "ls:encoded_by"
                    id3Tag          = "TENC"
                    localizationKey = "encoded_by"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:track_num"
                    id3Tag          = "TRCK"
                    localizationKey = "track_number"
                    tab             = "music" >
        <constraint type            = "numeric" />
    </metadataType>
    <metadataType   dcName          = "ls:disc_num"
                    id3Tag          = "TPOS"
                    localizationKey = "disc_number"
                    tab             = "music" >
        <constraint type            = "numeric" />
    </metadataType>
    <metadataType   dcName          = "ls:mood"
                    id3Tag          = "TMOO"
                    localizationKey = "mood"
                    tab             = "music"
    />
    <metadataType   dcName          = "dc:publisher"
                    id3Tag          = "TPUB"
                    localizationKey = "publishing_label"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:composer"
                    id3Tag          = "TCOM"
                    localizationKey = "composer"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:bitrate"
                    localizationKey = "bitrate"
                    tab             = "music" >
        <constraint type            = "numeric" />
    </metadataType>
    <metadataType   dcName          = "ls:channels"
                    localizationKey = "channels"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:samplerate"
                    localizationKey = "sample_rate"
                    tab             = "music" >
        <constraint type            = "numeric" />
    </metadataType>
    <metadataType   dcName          = "ls:encoder"
                    id3Tag          = "TSSE"
                    localizationKey = "encoding_software"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:crc"
                    localizationKey = "checksum"
    />
    <metadataType   dcName          = "ls:lyrics"
                    localizationKey = "lyrics"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:orchestra"
                    id3Tag          = "TPE2"
                    localizationKey = "orchestra_or_band"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:conductor"
                    id3Tag          = "TPE3"
                    localizationKey = "conductor"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:lyricist"
                    id3Tag          = "TEXT"
                    localizationKey = "lyricist"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:originallyricist"
                    id3Tag          = "TOLY"
                    localizationKey = "original_lyricist"
                    tab             = "music"
    />
    <metadataType   dcName          = "ls:radiostationname"
                    id3Tag          = "TRSN"
                    localizationKey = "radio_station_name"
    />
    <metadataType   dcName          = "ls:audiofileinfourl"
                    id3Tag          = "WOAF"
                    localizationKey = "audio_file_info_url"
    />
    <metadataType   dcName          = "ls:artisturl"
                    id3Tag          = "WOAR"
                    localizationKey = "artist_url"
    />
    <metadataType   dcName          = "ls:audiosourceurl"
                    id3Tag          = "WOAS"
                    localizationKey = "audio_source_url"
    />
    <metadataType   dcName          = "ls:radiostationurl"
                    id3Tag          = "WORS"
                    localizationKey = "radio_station_url"
    />
    <metadataType   dcName          = "ls:buycdurl"
                    id3Tag          = "WPAY"
                    localizationKey = "buy_cd_url"
    />
    <metadataType   dcName          = "ls:isrcnumber"
                    id3Tag          = "TSRC"
                    localizationKey = "isrc_number"
    />
    <metadataType   dcName          = "ls:catalognumber"
                    localizationKey = "catalog_number"
    />
    <metadataType   dcName          = "ls:originalartist"
                    id3Tag          = "TOPE"
                    localizationKey = "original_artist"
                    tab             = "music"
    />
    <metadataType   dcName          = "dc:rights"
                    id3Tag          = "TCOP"
                    localizationKey = "copyright"
                    tab             = "music"
    />
    <metadataType   dcName          = "dcterms:temporal"
                    localizationKey = "report_date_time"
                    tab             = "voice"
    />
    <metadataType   dcName          = "dcterms:spatial"
                    localizationKey = "report_location"
                    tab             = "voice"
    />
    <metadataType   dcName          = "dcterms:entity"
                    localizationKey = "report_organizations"
                    tab             = "voice"
    />
    <metadataType   dcName          = "dc:subject"
                    localizationKey = "subject"
                    tab             = "voice"
    />
</metadataTypeContainer>

